In [1]:
import matplotlib.pyplot as plt
import numpy as np
from hpob_handler import HPOBHandler
from methods.botorch import GaussianProcess
from methods.random_search import RandomSearch

c:\Users\82109\anaconda3\envs\my_pfns4bo\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
# valid_acquisitions = ["UCB", "EI", "PM", "PI", "qEI"]
valid_acquisitions = ["UCB"]
seeds = ["test0", "test1", "test2", "test3", "test4"]
acc_list = []
n_trials = 20

In [3]:
hpob_hdlr = HPOBHandler(root_dir="hpob-data/", mode="v3-test")
search_space_id =  hpob_hdlr.get_search_spaces()[0]
dataset_id = hpob_hdlr.get_datasets(search_space_id)[0]

Loading HPO-B handler
Loading data...


In [4]:
print(hpob_hdlr.get_search_spaces())
print(len(hpob_hdlr.get_search_spaces()))

['4796', '5527', '5636', '5859', '5860', '5891', '5906', '5965', '5970', '5971', '6766', '6767', '6794', '7607', '7609', '5889']
16


In [5]:
print(dataset_id)

3549


In [6]:
X = np.array(hpob_hdlr.meta_test_data[search_space_id][dataset_id]["X"])
y = np.array(hpob_hdlr.meta_test_data[search_space_id][dataset_id]["y"])

In [16]:
print(X.shape)
print(len(X))
print(y.shape)
print(((X<=1)&(X>=0)).sum()) # 0<= x <=1 => normalized
print(X)
# print(y)

(300, 3)
300
(300, 1)
900
[[1.66662628e-01 8.33329764e-01 2.56552908e-01]
 [3.33328261e-01 6.66659904e-01 7.73097596e-01]
 [1.66662628e-01 1.00000000e+00 2.28493537e-01]
 [3.33328261e-01 8.33329764e-01 5.93351938e-01]
 [1.66662628e-01 1.66658590e-01 6.75823972e-01]
 [8.33331549e-01 1.00000000e+00 7.80085039e-01]
 [6.66663285e-01 0.00000000e+00 7.40963286e-01]
 [1.66662628e-01 3.33323190e-01 7.16888445e-01]
 [6.66663285e-01 8.33329764e-01 3.55799497e-01]
 [6.66663285e-01 0.00000000e+00 8.13913241e-01]
 [4.99995398e-01 8.33329764e-01 8.96036519e-01]
 [4.99995398e-01 1.66658590e-01 4.13927886e-01]
 [4.99995398e-01 8.33329764e-01 5.04402686e-01]
 [1.00000000e+00 8.33329764e-01 1.04222837e-01]
 [3.33328261e-01 3.33323190e-01 7.52984709e-01]
 [0.00000000e+00 6.66659904e-01 4.69491777e-01]
 [6.66663285e-01 3.33323190e-01 8.26505373e-03]
 [8.33331549e-01 4.99990796e-01 2.23728617e-01]
 [0.00000000e+00 6.66659904e-01 5.38643402e-02]
 [3.33328261e-01 1.66658590e-01 4.49316341e-01]
 [0.00000000e+

In [18]:
hpob_hdlr.meta_test_data[search_space_id].keys()

dict_keys(['3549', '3918', '9903', '23'])

In [20]:
print(hpob_hdlr.bo_initializations[search_space_id][dataset_id])

{'test0': [220, 281, 83, 149, 269], 'test1': [244, 148, 221, 44, 249], 'test2': [24, 180, 12, 117, 31], 'test3': [214, 72, 267, 286, 8], 'test4': [123, 74, 228, 110, 45]}


In [ ]:
for acq_name in valid_acquisitions:
    acc_per_method = []
    for seed in seeds:
        print("Using ", acq_name, " as acquisition function...")

        #define the HPO method
        method = GaussianProcess(acq_name=acq_name)

        #evaluate the HPO method
        acc = hpob_hdlr.evaluate(method, search_space_id = search_space_id, 
                                                dataset_id = dataset_id,
                                                seed = seed,
                                                n_trials = n_trials)

        acc_per_method.append(acc)

    plt.plot(np.array(acc_per_method).mean(axis=0))
plt.legend(valid_acquisitions)
plt.show()

### train data

In [2]:
hpob_hdlr = HPOBHandler(root_dir="hpob-data/", mode="v3-train-augmented")

Loading HPO-B handler
Loading data...


In [11]:
print(len(hpob_hdlr.get_meta_train_search_spaces()))

176


In [ ]:
cnt = 0
for search_space_id in hpob_hdlr.get_meta_train_search_spaces():
    for dataset_id in hpob_hdlr.get_meta_train_datasets(search_space_id):
        print(f'search space id = {search_space_id}, dataset id = {dataset_id}')
        X = np.array(hpob_hdlr.meta_train_data[search_space_id][dataset_id]["X"])
        y = np.array(hpob_hdlr.meta_train_data[search_space_id][dataset_id]["y"])

        print(f'X shape = {X.shape}, y shape = {y.shape}')
        cnt += 1
print()
print(f'Total number of combinations = {cnt}')